### ISSUE TITLE
[Feature] The mod currently crashes when using on Quilt Loader. Would be nice to have it working there if possible.

### ISSUE THREAD

**Issue by frikinjay** [JustAlittleWolf/modpackLoaderFabric#1]
Crash Report:
```
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'modpackloaderfabric'!
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:62)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:60)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:45)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:32)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.launch.knot.KnotHelper.launchClient(KnotHelper.java:28)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NullPointerException: entry
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at java.base/java.util.zip.ZipFile.getInputStream(ZipFile.java:354)
	at java.base/java.util.jar.JarFile.getInputStream(JarFile.java:842)
	at net.justalittlewolf.modpackloaderfabric.ModpackLoaderFabric.updateMods(ModpackLoaderFabric.java:93)
	at net.justalittlewolf.modpackloaderfabric.ModpackLoaderFabric.onInitialize(ModpackLoaderFabric.java:77)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startClient$0(Hooks.java:52)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:32)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:58)
	... 13 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:62)
	at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:60)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:45)
	at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:32)
	at org.quiltmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)

-- Initialization --
Details:
	Modules: ~~ERROR~~ LinkageError: loader constraint violation: when resolving interface method 'int com.sun.jna.platform.win32.Version.GetFileVersionInfoSize(java.lang.String, com.sun.jna.ptr.IntByReference)' the class loader net.fabricmc.loader.launch.knot.KnotClassLoader @56f0cc85 of the current class, net/minecraft/class_6498, and the class loader 'app' for the method's defining class, com/sun/jna/platform/win32/Version, have different Class objects for the type com/sun/jna/ptr/IntByReference used in the signature (net.minecraft.class_6498 is in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @56f0cc85, parent loader net.fabricmc.loader.launch.knot.KnotClassLoader$DynamicURLClassLoader @6ad59d92; com.sun.jna.platform.win32.Version is in unnamed module of loader 'app')
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.launch.knot.KnotHelper.launchClient(KnotHelper.java:28)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by JustAlittleWolf** [comment]
Thanks for your suggestion. Unfortunately mod development has been discontinued as modrinth just released their own [modpack manager](https://modrinth.com/modpacks).

**Comment by frikinjay** [comment]
I see, I'd still love to get this fixed if possible for a project this would really help with. I can commission a fix if youre open to commissions.

**Comment by JustAlittleWolf** [comment]
Absolutely, although I have to say I'm quite new to github. If you need me to enable some permissions for you to be able to commission a fix let me know.

**Comment by frikinjay** [comment]
Oh sorry, I meant I can maybe have you fix the issue in exchange of a price if youre open to that.

**Comment by JustAlittleWolf** [comment]
Oh ok, no need to pay me. I think your game crashed, not because you were using quilt, but because you had a quilt mod in your mods directory (my mod checks for duplicate mods and it didnt find fabric.mod.json in that mod so it crashed). I did a quick hotfix 0.3.3. I'm not entirely sure if it works for your specific setup so let me know if it did.
You can find the new version under the releases tab.

**Comment by frikinjay** [comment]
Ah I see, thanks for the fix : )
